/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as IaHealthRouteImport } from './routes/ia-health'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as BookPaymentRouteImport } from './routes/book.payment'
import { Route as BookTravelersRouteImport } from './routes/book.travelers'
import { Route as BookingsReferenceRouteImport } from './routes/bookings.$reference'
import { Route as FlightsIndexRouteImport } from './routes/flights.index'
import { Route as FlightsOfferIdRouteImport } from './routes/flights.$offerId'
import { Route as BookConfirmationReferenceRouteImport } from './routes/book.confirmation.$reference'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const IaHealthRoute = IaHealthRouteImport.update({
  id: '/ia-health',
  path: '/ia-health',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const BookPaymentRoute = BookPaymentRouteImport.update({
  id: '/book/payment',
  path: '/book/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTravelersRoute = BookTravelersRouteImport.update({
  id: '/book/travelers',
  path: '/book/travelers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsReferenceRoute = BookingsReferenceRouteImport.update({
  id: '/$reference',
  path: '/$reference',
  getParentRoute: () => BookingsRoute,
} as any)
const FlightsIndexRoute = FlightsIndexRouteImport.update({
  id: '/flights/',
  path: '/flights/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsOfferIdRoute = FlightsOfferIdRouteImport.update({
  id: '/flights/$offerId',
  path: '/flights/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmationReferenceRoute =
  BookConfirmationReferenceRouteImport.update({
    id: '/book/confirmation/$reference',
    path: '/book/confirmation/$reference',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/hotels': typeof HotelsRoute
  '/ia-health': typeof IaHealthRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/support': typeof SupportRoute
  '/trips': typeof TripsRoute
  '/book/payment': typeof BookPaymentRoute
  '/book/travelers': typeof BookTravelersRoute
  '/bookings/$reference': typeof BookingsReferenceRoute
  '/flights/$offerId': typeof FlightsOfferIdRoute
  '/flights/': typeof FlightsIndexRoute
  '/book/confirmation/$reference': typeof BookConfirmationReferenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/hotels': typeof HotelsRoute
  '/ia-health': typeof IaHealthRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/support': typeof SupportRoute
  '/trips': typeof TripsRoute
  '/book/payment': typeof BookPaymentRoute
  '/book/travelers': typeof BookTravelersRoute
  '/bookings/$reference': typeof BookingsReferenceRoute
  '/flights/$offerId': typeof FlightsOfferIdRoute
  '/flights': typeof FlightsIndexRoute
  '/book/confirmation/$reference': typeof BookConfirmationReferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/hotels': typeof HotelsRoute
  '/ia-health': typeof IaHealthRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/support': typeof SupportRoute
  '/trips': typeof TripsRoute
  '/book/payment': typeof BookPaymentRoute
  '/book/travelers': typeof BookTravelersRoute
  '/bookings/$reference': typeof BookingsReferenceRoute
  '/flights/$offerId': typeof FlightsOfferIdRoute
  '/flights/': typeof FlightsIndexRoute
  '/book/confirmation/$reference': typeof BookConfirmationReferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/hotels'
    | '/ia-health'
    | '/notifications'
    | '/profile'
    | '/support'
    | '/trips'
    | '/book/payment'
    | '/book/travelers'
    | '/bookings/$reference'
    | '/flights/$offerId'
    | '/flights/'
    | '/book/confirmation/$reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/hotels'
    | '/ia-health'
    | '/notifications'
    | '/profile'
    | '/support'
    | '/trips'
    | '/book/payment'
    | '/book/travelers'
    | '/bookings/$reference'
    | '/flights/$offerId'
    | '/flights'
    | '/book/confirmation/$reference'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/hotels'
    | '/ia-health'
    | '/notifications'
    | '/profile'
    | '/support'
    | '/trips'
    | '/book/payment'
    | '/book/travelers'
    | '/bookings/$reference'
    | '/flights/$offerId'
    | '/flights/'
    | '/book/confirmation/$reference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  HotelsRoute: typeof HotelsRoute
  IaHealthRoute: typeof IaHealthRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SupportRoute: typeof SupportRoute
  TripsRoute: typeof TripsRoute
  BookPaymentRoute: typeof BookPaymentRoute
  BookTravelersRoute: typeof BookTravelersRoute
  FlightsOfferIdRoute: typeof FlightsOfferIdRoute
  FlightsIndexRoute: typeof FlightsIndexRoute
  BookConfirmationReferenceRoute: typeof BookConfirmationReferenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-health': {
      id: '/ia-health'
      path: '/ia-health'
      fullPath: '/ia-health'
      preLoaderRoute: typeof IaHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/payment': {
      id: '/book/payment'
      path: '/book/payment'
      fullPath: '/book/payment'
      preLoaderRoute: typeof BookPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/travelers': {
      id: '/book/travelers'
      path: '/book/travelers'
      fullPath: '/book/travelers'
      preLoaderRoute: typeof BookTravelersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$reference': {
      id: '/bookings/$reference'
      path: '/$reference'
      fullPath: '/bookings/$reference'
      preLoaderRoute: typeof BookingsReferenceRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/flights/': {
      id: '/flights/'
      path: '/flights'
      fullPath: '/flights/'
      preLoaderRoute: typeof FlightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/$offerId': {
      id: '/flights/$offerId'
      path: '/flights/$offerId'
      fullPath: '/flights/$offerId'
      preLoaderRoute: typeof FlightsOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirmation/$reference': {
      id: '/book/confirmation/$reference'
      path: '/book/confirmation/$reference'
      fullPath: '/book/confirmation/$reference'
      preLoaderRoute: typeof BookConfirmationReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookingsRouteChildren {
  BookingsReferenceRoute: typeof BookingsReferenceRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsReferenceRoute: BookingsReferenceRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRouteWithChildren,
  HotelsRoute: HotelsRoute,
  IaHealthRoute: IaHealthRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SupportRoute: SupportRoute,
  TripsRoute: TripsRoute,
  BookPaymentRoute: BookPaymentRoute,
  BookTravelersRoute: BookTravelersRoute,
  FlightsOfferIdRoute: FlightsOfferIdRoute,
  FlightsIndexRoute: FlightsIndexRoute,
  BookConfirmationReferenceRoute: BookConfirmationReferenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
